author: Hang Yu
description: Hang Yu's blog
keyword: vuejs

excerpt_link: Read more

menu:
 Home: /
 Series: /series/
 Tags: /tags/
 Archives: /archives/
#  Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set utterances, gitment, uyan or disqus
comment: gitment

# utterances config
utterances_repo:                # e.g. GitHubAccount/RepoForUtterances
utterances_issue_term: pathname # you can see other available options at 'https://utteranc.es/'
utterances_theme: github-light  # you can see other available options at 'https://utteranc.es/'

# gitment config
gitment_owner: ysg00
gitment_repo: blog
gitment_oauth_id: 63a062023b7fec962d18
gitment_oauth_secret: aebd075b33f7a4c1bede9fbd138c6f3d45d8d64f

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
google_analytics: 
# disqus config
disqus_shortname: 

about: 
  banner: ""
  # avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "Hello World"
  # weibo_username:
  # twitter_username:
  github_username: ysg00
  # zhihu_username:
  # douban_username:
  linkedin_username: h-y

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Local Search Support
local_search:
  enable: true